version: '3'
services:

  airflowproject:
    image: airflow-project:latest
    environment:
      - AWS_ACCESS_KEY_ID=AKIAXYKJTWHWWSIZBQXI
      - AWS_SECRET_ACCESS_KEY=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
      - YOUTUBE_API_KEY=AIzaSyC9e_LXg_F5v8rdjgg2qj3cWDjrQ8ws2Ow
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: airflow standalone